stopzaim/customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('customers_list', views.CustomerListView.as_view(), name='list'),
    path('delete-customer/<int:pk>/', views.delete_customer, name='delete_customer'),
    path('create_customer/', views.CustomerCreateView.as_view(), name="create_customer"),
    path('update_customer/<int:pk>/', views.CustomerUpdateView.as_view(), name="update_customer"),
    path('update_customer_tables/<int:pk>/<str:table>/', views.customer_formset_update, name="update_customer_tables"),
    path('companies_list', views.CompanyListView.as_view(), name='companies_list'),
    path('create_company/', views.CompanyCreateView.as_view(), name="create_company"),
    path('update_company/<int:pk>/', views.CompanyUpdateView.as_view(), name="update_company"),
    path('delete-company/<int:pk>/', views.delete_company, name='delete_company'),
]

stopzaim/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home")
]

stopzaim/stopzaim/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("customer/", include('customers.urls'))
]

stopzaim/customers/forms.py
from django import forms
from . import models

common_input_class = 'form-control mb-2'
text_widget = forms.TextInput(attrs={'class': common_input_class})
select_widget = forms.Select(attrs={'class': common_input_class})
date_widget = forms.DateInput(attrs={'class': common_input_class,'type': 'date'})
number_widget = forms.NumberInput(attrs={'class':'form-control'})
text_area_widget = forms.Textarea(attrs={'class': common_input_class})
checkbox_widget = forms.CheckboxInput(attrs={'class': 'form-check-input'})

class CustomerForm(forms.ModelForm):
    class Meta:
        model = models.Customer
        exclude = []
        widgets = {
            'first_name': text_widget,
            'middle_name': text_widget,
            'surname': text_widget,
            'gender': select_widget,
            'birthdate': date_widget,
            'phone': text_widget,
            'tax_id': text_widget,
            'snils': text_widget,
            'passport_series': text_widget,
            'passport_number': text_widget,
            'passport_issuer': text_widget,
            'passport_issue_date': date_widget,
            'passport_issuer_code': text_widget,
            'address': text_widget,
            'birthplace': text_widget,
            'tax_inspection': select_widget,
            'occupation': select_widget,
            'previous_year_income': text_widget,
            'job': select_widget,
            'position': text_widget,
            'sro': select_widget,
            'arbitration_court': select_widget,
            'gosuslugi': text_widget,
            'application_date': date_widget,
            'comments': text_area_widget,
            'is_married': checkbox_widget,
            'spouse_name': text_widget
        }

    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.required = False
                field.widget.attrs['required'] = False

class CompanyForm(forms.ModelForm):
    class Meta:
        model = models.Company
        fields = ['name']
        widgets = {
            'name': text_widget
        }

class CustomerLoanForm(forms.ModelForm):
    class Meta:
        model = models.CustomerLoan
        exclude = []
        widgets = {
            'company': select_widget,
            'amount': number_widget
        }

CustomerLoansFormset = forms.inlineformset_factory(
    models.Customer, models.CustomerLoan, form=CustomerLoanForm,
    extra=0, can_delete=True, can_delete_extra = True 
)

class CustomerChildForm(forms.ModelForm):
    class Meta:
        model = models.CustomerChild
        exclude = []
        widgets = {
            'name': text_widget,
            'gender': select_widget,
            'birthdate': date_widget, 
        }

CustomerChildrenFormset = forms.inlineformset_factory(
    models.Customer, models.CustomerChild, form=CustomerChildForm,
    extra=0, can_delete=True, can_delete_extra = True 
)

class CustomerBankAccountForm(forms.ModelForm):
    class Meta:
        model = models.CustomerBankAccount
        exclude = []
        widgets = {
            'type': select_widget,
            'currency': select_widget,
            'account_number': text_widget,
            'bank': select_widget,
            'balance': number_widget,
            'opening_date': date_widget
        }          

CustomerBankAccountFormset = forms.inlineformset_factory(
    models.Customer, models.CustomerBankAccount, form=CustomerBankAccountForm,
    extra=0, can_delete=True, can_delete_extra = True 
)

class CustomerPayableForm(forms.ModelForm):
    class Meta:
        model = models.CustomerPayable
        exclude = []
        widgets = {
            'type': select_widget,
            'lender': select_widget,
            'account_number': text_widget,
            'basis': text_widget,
            'gross_amount': number_widget,
            'net_amount': number_widget,
            'penalties_amount': number_widget,
        }          

CustomerPayableFormset = forms.inlineformset_factory(
    models.Customer, models.CustomerPayable, form=CustomerPayableForm,
    extra=0, can_delete=True, can_delete_extra = True 
)

class CustomerExecutiveDocForm(forms.ModelForm):
    class Meta:
        model = models.CustomerExecutiveDoc
        exclude = []
        widgets = {
            'type': select_widget,
            'date': date_widget,
            'doc_number': text_widget,
            'executor': text_widget,
            'content': text_widget,
        }          

CustomerExecutiveDocFormset = forms.inlineformset_factory(
    models.Customer, models.CustomerExecutiveDoc, form=CustomerExecutiveDocForm,
    extra=0, can_delete=True, can_delete_extra = True 
)

class CustomerMandatoryPaymentForm(forms.ModelForm):
    class Meta:
        model = models.CustomerMandatoryPayment
        exclude = []
        widgets = {
            'tax_name': select_widget,
            'arrears_amount': number_widget,
            'penalties_amount': number_widget
        }          

CustomerMandatoryPaymentFormset = forms.inlineformset_factory(
    models.Customer, models.CustomerMandatoryPayment, form=CustomerMandatoryPaymentForm,
    extra=0, can_delete=True, can_delete_extra = True 
)

class CustomerRealtyForm(forms.ModelForm):
    class Meta:
        model = models.CustomerRealty
        exclude = []
        widgets = {
            'name': text_widget,
            'type': select_widget,
            'property_type': select_widget,
            'area': number_widget,
            'acquiring_basis': text_widget,
            'pledge': text_widget,
            'address': text_widget,
        }

CustomerRealtyFormSet = forms.inlineformset_factory(
    models.Customer, models.CustomerRealty, form=CustomerRealtyForm,
    extra=0, can_delete=True, can_delete_extra = True
)

class CustomerTransportForm(forms.ModelForm):
    class Meta:
        model = models.CustomerTransport
        exclude = []
        widgets = {
            'name': text_widget,
            'type': select_widget,
            'property_type': select_widget,
            'cost': number_widget,
            'production_year': text_widget,
            'plate_number': text_widget,
            'pledge': text_widget,
            'address': text_widget,
        }        

CustomerTransportFormset = forms.inlineformset_factory(
    models.Customer, models.CustomerTransport, form=CustomerTransportForm,
    extra=0, can_delete=True, can_delete_extra = True 
)

stopzaim/customers/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from . import forms
from . import models
from django.urls import reverse

def get_customer_navs(title, is_new):
    navs = [
            {'title': 'Общие сведения', 'link': 'customers:update_customer' },
            {'title': 'Дети', 'link': 'customers:update_customer_tables', 'table': 'children'},
            {'title': 'Банковские счета', 'link': 'customers:update_customer_tables', 'table': 'bank_accounts'},
            {'title': 'Кредиторы', 'link': 'customers:update_customer_tables', 'table': 'payables'},
            {'title': 'Исполнительные документы', 'link': 'customers:update_customer_tables', 'table': 'executive_docs'},
            {'title': 'Обязательные платежи', 'link': 'customers:update_customer_tables', 'table': 'mandatory_payments'},
            {'title': 'Недвижимость', 'link': 'customers:update_customer_tables', 'table': 'realty'},
            {'title': 'Движимое имущество', 'link': 'customers:update_customer_tables', 'table': 'transports'}       
        ]
    for nav in navs:
        if (nav['title']==title):
            nav['active'] = True
            nav['disabled'] = True
        else:
            nav['active'] = False
            nav['disabled'] = is_new
    return navs

class CustomerListView(ListView):
    model = models.Customer
    template_name = 'customers/customer_list.html'
    context_object_name = 'customers'
    def get_context_data(self, **kwargs):
        ctx_data = super().get_context_data(**kwargs)
        ctx_data['delete_url'] = 'customers:delete_customer'
        return ctx_data
    
def delete_customer(request, pk):
    try:
        obj = models.Customer.objects.get(id=pk)
    except obj.DoesNotExist:
        messages.success(
            request, 'Объект не существует'
            )
        return redirect('customers:list')

    obj.delete()
    messages.success(
            request, 'Строка удалена успешно'
            )
    return redirect('customers:list')   


class CustomerCreateView(CreateView):
    form_class = forms.CustomerForm
    model = models.Customer
    template_name = 'customers/customer_create.html'

    def form_valid(self, form):
        self.object = form.save()
        return redirect('customers:update_customer', pk=self.object.id)  

    def get_context_data(self, **kwargs):
        ctx_data = super().get_context_data(**kwargs)
        ctx_data['customer'] = 0
        ctx_data['navs'] = get_customer_navs('Общие сведения',True)
        return ctx_data

class CustomerUpdateView(UpdateView):
    form_class = forms.CustomerForm
    model = models.Customer
    template_name = 'customers/customer_create.html'

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.request.path_info)    

    def get_context_data(self, **kwargs):
        ctx_data = super().get_context_data(**kwargs)
        ctx_data['customer'] = self.object
        ctx_data['navs'] = get_customer_navs('Общие сведения',False)
        return ctx_data

def customer_formset_update(request, pk, table):
    customer = models.Customer.objects.get(id=pk)
    if table=='children':
        formset_data = {
            'formset_model': forms.CustomerChildrenFormset,
            'formset_title': 'Дети',
            'formset_name': 'customerchild'} 
    elif table=='bank_accounts':
        formset_data = {
            'formset_model': forms.CustomerBankAccountFormset,
            'formset_title': 'Банковские счета',
            'formset_name': 'customerbankaccount'}
    elif table=='payables':
        formset_data = {
            'formset_model': forms.CustomerPayableFormset,
            'formset_title': 'Кредиторы',
            'formset_name': 'customerpayable'}
    elif table=='executive_docs':
        formset_data = {
            'formset_model': forms.CustomerExecutiveDocFormset,
            'formset_title': 'Исполнительные документы',
            'formset_name': 'customerexecutivedoc'}
    elif table=='mandatory_payments':
        formset_data = {
            'formset_model': forms.CustomerMandatoryPaymentFormset,
            'formset_title': 'Обязательные платежи',
            'formset_name': 'customermandatorypayment'}
    elif table=='realty':
        formset_data = {
            'formset_model': forms.CustomerRealtyFormSet,
            'formset_title': 'Недвижимость',
            'formset_name': 'customerrealty'}
    elif table=='transports':
        formset_data = {
            'formset_model': forms.CustomerTransportFormset,
            'formset_title': 'Движимое имущество',
            'formset_name': 'customertransport'}
    if request.method == 'POST':
        formset = formset_data['formset_model'](request.POST or None, instance=customer)
        if formset.is_valid():
            for form in formset:
                print(form.cleaned_data.get('name', False))
                if form.cleaned_data.get('DELETE', False):
                    print('test')
            formset.save()
            return redirect(request.path_info)
    else:
        formset = formset_data['formset_model'](instance=customer)
    ctx_data = {'customer': customer,
                   'formset': formset,
                   'formset_name': formset_data['formset_name'],
                   'formset_title': formset_data['formset_title'],
                   'navs': get_customer_navs(formset_data['formset_title'],False)}
    return render(request,'customers/customer_formsets_create.html',ctx_data)    

class CompanyListView(ListView):
    model = models.Company
    template_name = 'customers/companies_list.html'
    context_object_name = 'companies'
    def get_context_data(self, **kwargs):
        ctx_data = super().get_context_data(**kwargs)
        ctx_data['delete_url'] = 'customers:delete_company'
        return ctx_data

class CompanyCreateView(CreateView):
    form_class = forms.CompanyForm
    model = models.Company
    template_name = 'customers/company_create.html'


    def form_valid(self, form):
        self.object = form.save()
        return redirect('customers:update_company', pk=self.object.id)  

    def get_context_data(self, **kwargs):
        ctx_data = super().get_context_data(**kwargs)
        ctx_data['company'] = 0
        return ctx_data
    
class CompanyUpdateView(UpdateView):
    form_class = forms.CompanyForm
    model = models.Company
    template_name = 'customers/company_create.html'

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.request.path_info)    

    def get_context_data(self, **kwargs):
        ctx_data = super().get_context_data(**kwargs)
        ctx_data['company'] = self.object
        return ctx_data
    
def delete_company(request, pk):
    try:
        obj = models.Company.objects.get(id=pk)
    except obj.DoesNotExist:
        messages.success(
            request, 'Объект не существует'
            )
        return redirect('customers:companies_list')

    obj.delete()
    messages.success(
            request, 'Строка удалена успешно'
            )
    return redirect('customers:companies_list')  

stopzaim/customers/templates/customers/companies_list.html
{% extends 'main/base.html' %}

{% block title %}Список контрагентов{% endblock %}

{% block header %}
    Список контрагентов
{% endblock %}
{% block content %}
<a class="btn btn-primary" href="{% url 'customers:create_company' %}">Добавить контрагента</a>
<div class="list-group mt-2">
    {% for company in companies %}
    <div class="d-flex">
        <a href="{% url 'customers:update_company' company.id %}" class="list-group-item list-group-item-action">{{company.name }}</a>
        <button type="button" class="btn btn-secondary my-1" data-toggle="modal" data-target="#exampleModal{{company.id}}">
            Удалить
        </button>        
    </div>
    <!-- Modal -->
    {% include "customers/partials/modal_delete_confirmation.html" with delete_url=delete_url id=company.id %}
    {% endfor %}
</div>
{% endblock content %}

stopzaim/customers/templates/customers/company_create.html
{% extends 'main/base.html' %}

{% block title %}
{% if company %}
    {{ company.name }}
{% else %}
    Новый контрагент
{% endif %}
{% endblock %}

{% block header %}
{% if company %}
    {{ company.name }}
{% else %}
    Новый контрагент
{% endif %}
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="card border-0 mt-2">
        {{ form.name.label }}
        {{ form.name }}
    </div>
    <br>
    <button class="btn btn-success" type="submit">
        Записать
    </button>
</form>
{% include 'customers/partials/form_unsaved_changes.html' %}
{% endblock %}

stopzaim/customers/templates/customers/customer_create.html
{% extends 'main/base.html' %}

{% block title %}
{% if customer %}
    {{ customer }}: общие сведения
{% else %}
    Новый клиент: общие сведения
{% endif %}
{% endblock %}

{% block header %}
{% if customer %}
    {{ customer }}: общие сведения
{% else %}
    Новый клиент: общие сведения
{% endif %}
{% endblock %}
{% block content %}

{% include 'customers/partials/customer_navs.html' with navs=navs customer=customer%}
<form method="post">
    {% csrf_token %}
    <button class="btn btn-success mt-2" type="submit">
        Записать
    </button>
    <div class="container-fluid"> 
        <div class="row">
            <div class="col">
                {{ form.surname.label_tag }}
                {{ form.surname }}
            </div>
            <div class="col">
                {{ form.first_name.label_tag }}
                {{ form.first_name }}              
            </div>
            <div class="col">
                {{ form.middle_name.label_tag }}
                {{ form.middle_name }}               
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.gender.label_tag }}
                {{ form.gender }}
            </div>
            <div class="col">
                {{ form.birthdate.label_tag }}
                {{ form.birthdate }}              
            </div>
            <div class="col">
                {{ form.phone.label_tag }}
                {{ form.phone }}               
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.tax_id.label_tag }}
                {{ form.tax_id }}
            </div>
            <div class="col">
                {{ form.snils.label_tag }}
                {{ form.snils }}              
            </div>
        </div>
        <p class="my-1">
            <a class="btn btn-secondary" data-toggle="collapse" href="#collapsePassport" role="button" aria-expanded="false"
                aria-controls="collapsePassport">
                Паспорт серия {{customer.passport_series}} номер {{customer.passport_number}} выданный {{customer.passport_issue_date|date:"d.m.Y"}} 
                {{customer.passport_issuer}} код подразделения {{customer.passport_issuer_code}}
            </a>
        </p>
        <div class="collapse" id="collapsePassport">
            <div class="card card-body">
                <div class="row">
                    <div class="col">
                        {{ form.passport_series.label_tag }}
                        {{ form.passport_series }}
                    </div>
                    <div class="col">
                        {{ form.passport_number.label_tag }}
                        {{ form.passport_number }}              
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {{ form.passport_issuer.label_tag }}
                        {{ form.passport_issuer }}
                    </div>
                    <div class="col">
                        {{ form.passport_issue_date.label_tag }}
                        {{ form.passport_issue_date }}              
                    </div>
                    <div class="col">
                        {{ form.passport_issuer_code.label_tag }}
                        {{ form.passport_issuer_code }}               
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.address.label_tag }}
                {{ form.address }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.birthplace.label_tag }}
                {{ form.birthplace }}
            </div>
            <div class="col">
                {{ form.tax_inspection.label_tag }}
                {{ form.tax_inspection }}              
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.occupation.label_tag }}
                {{ form.occupation }}
            </div>
            <div class="col">
                {{ form.previous_year_income.label_tag }}
                {{ form.previous_year_income }}              
            </div>
        </div>    
        <div class="row">
            <div class="col">
                {{ form.job.label_tag }}
                {{ form.job }}
            </div>
            <div class="col">
                {{ form.position.label_tag }}
                {{ form.position }}              
            </div>
        </div>     
        <div class="row">
            <div class="col">
                {{ form.sro.label_tag }}
                {{ form.sro }}
            </div>
            <div class="col">
                {{ form.arbitration_court.label_tag }}
                {{ form.arbitration_court }}              
            </div>
        </div>  
        <div class="row">
            <div class="col">
                {{ form.gosuslugi.label_tag }}
                {{ form.gosuslugi }}              
            </div>
            <div class="col">
                {{ form.application_date.label_tag }}
                {{ form.application_date }}              
            </div>
        </div>    
        <div class="row">
            <div class="col">
                <br>
                <div class="form-check">
                    {{form.is_married.label_tag}}
                    {{form.is_married}}
                </div>        
            </div>
            <div class="col">
                {{form.spouse_name.label_tag}}
                {{form.spouse_name}}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.comments.label_tag }}
                {{ form.comments }}              
            </div>
        </div>  
    </div>
</form>
{% include 'customers/partials/form_unsaved_changes.html' %}
{% endblock %}

stopzaim/customers/templates/customers/customer_formsets_create.html
{% extends 'main/base.html' %}

{% block title %} {{ customer }}: {{formset_title|lower}}{% endblock %}

{% block header %}
{{ customer }}: {{formset_title|lower}}
{% endblock %}
{% block content %}
{% include 'customers/partials/customer_navs.html' with navs=navs customer=customer%}
{% include 'customers/partials/customer_table_form.html' with formset=formset formset_name=formset_name %}
{% include 'customers/partials/form_unsaved_changes.html' %}
{% endblock %}

stopzaim/customers/templates/customers/customer_list.html
{% extends 'main/base.html' %}

{% block title %}Список клиентов{% endblock %}

{% block header %}
    Список клиентов
{% endblock %}
{% block content %}
<a class="btn btn-success" href="{% url 'customers:create_customer' %}">Добавить клиента</a>
<div class="list-group mt-2">
    {% for customer in customers %}
    <div class="d-flex">
        <a href="{% url 'customers:update_customer' customer.id %}" class="list-group-item list-group-item-action">{{customer}}</a>
        <button type="button" class="btn btn-secondary my-1" data-toggle="modal" data-target="#exampleModal{{customer.id}}">
            Удалить
        </button>        
    </div>
    <!-- Modal -->
    {% include "customers/partials/modal_delete_confirmation.html" with delete_url=delete_url id=customer.id %}
    {% endfor %}
</div>
{% endblock content %}