stopzaim/customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('customers_list', views.CustomerListView.as_view(), name='list'),
    path('delete-customer/<int:pk>/', views.delete_customer, name='delete_customer'),
    path('create_customer/', views.CustomerCreateView.as_view(), name="create_customer"),
    path('update_customer/<int:pk>/', views.CustomerUpdateView.as_view(), name="update_customer"),
    path('update_customer_tables/<int:pk>/<str:table>/', views.customer_formset_update, name="update_customer_tables"),
    path('companies_list', views.CompanyListView.as_view(), name='companies_list'),
    path('create_company/', views.CompanyCreateView.as_view(), name="create_company"),
    path('update_company/<int:pk>/', views.CompanyUpdateView.as_view(), name="update_company"),
    path('delete-company/<int:pk>/', views.delete_company, name='delete_company'),
]

stopzaim/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home")
]

stopzaim/stopzaim/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("customer/", include('customers.urls'))
]

stopzaim/main/models.py
from django.db import models

stopzaim/main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

stopzaim/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'main/css/tcal.css' %}">
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
        </script>
    <script src="{% static 'main/js/tcal.js' %}"></script>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 p-3">
                <h3>Стопзайм</h3>
                <nav class="nav flex-column">
                    <a class="nav-link" href="{% url 'customers:list' %}">
                        <i class="fa-solid fa-person"></i> Клиенты
                    </a>
                    <a class="nav-link" href="{% url 'customers:companies_list' %}">
                        <i class="fa-solid fa-business-time"></i> Контрагенты
                    </a>                    
                </nav>
            </div>
            <div class="col-10 p-3">
                <div class="mb-3">
                    <h4>
                        {% block header %}
                        {% endblock %}
                    </h4>
                </div>        
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
        </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
        </script>
</body>

</html>

stopzaim/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title  %}{{ title }}{% endblock %}

{% block content  %}
    <div class="features">
        <h1>{{ title }}</h1>
        <p>CRM система для учета клиентов юридической фирмы специализирующейся на банкротстве физических лиц</p>
        <button class="btn btn-warning">На страницу про нас</button>
    </div>
{% endblock %}